version: "3.5"

networks:
  remote-cache:
    driver: bridge

services:
  bazel_cache:
    build: .
    container_name: bazel_cache
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      remote-cache:
        aliases:
          - remote
    ports:
      - "9001:9001"
